GET http://localhost:3003/balances/46444f3b-c687-4db8-b08a-d8ad56fb2a3c HTTP/1.1

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "e01a8e9c-f875-4e04-a737-490cfa6ebc4a",
    "account_id_to": "46444f3b-c687-4db8-b08a-d8ad56fb2a3c",
    "amount": 100
}